
export enum AppPhase {
  SOUL_SCAN = 'SOUL_SCAN',
  MULTIVERSE = 'MULTIVERSE',
  SIMULATION = 'SIMULATION',
  SKILL_TREE = 'SKILL_TREE',
  TUTOR = 'TUTOR',
  LIFE_SIMULATION = 'LIFE_SIMULATION'
}

export type Language = 'zh' | 'en';

export interface RPGStats {
  intelligence: number; // 智力 (逻辑)
  creativity: number;   // 创造力 (艺术)
  charisma: number;     // 魅力 (社交)
  stamina: number;      // 耐力 (抗压)
  tech: number;         // 技术力
}

export interface UserProfile {
  name: string;
  major: string; // Replace education with major/background
  hobbies: string[]; // Bilibili, Games, etc.
  hiddenTalent: string; // "Hidden Data"
  rpgStats?: RPGStats; // Generated by AI
  archetype?: string; // e.g., "Cyber Mystic", "Data Mercenary"
}

export interface CareerPath {
  id: string;
  category: string;
  jobs: JobOption[];
}

export interface JobOption {
  id: string;
  title: string;
  description: string;
  skills: string[];
  salary: string;
  dayInLife: string; // "Life Style" translation
  pitfalls: string;  // "Reality Check"
  matchScore: number;
}

export interface Resource {
  id: string;
  title: string;
  type: 'Book' | 'Video' | 'GitHub' | 'Mission';
  description: string;
  xp: number; // Gamification
  url?: string; // External Link
  completed?: boolean;
}

export interface SimulationStep {
  scenario: string;
  options: {
    id: string;
    text: string;
  }[];
}

export interface SimulationResult {
  outcome: string;
  score: number; // Adaptation score
  feedback: string;
}

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
  isBoss?: boolean; // For Boss Battle mode
}
